CityArrayWeb/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CityArrayDAL.UnitOfWork;
using AutoMapper;
using CityArrayDAL.Model;
using System.IO;
using CityArrayWeb.ModelView;
using System.Net;
using System.Linq.Dynamic;
using PagedList;
using log4net;
using Newtonsoft.Json;

namespace CityArrayWeb.Controllers
{
    public class CityController : Controller
    {
        private IRepo db;
        private ILog logger;

        public CityController(IRepo repo)
        {
            db = repo;
            logger = LogManager.GetLogger(this.GetType());
        }

        public ActionResult Info(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cities = db.Cities.GetOne(id.Value);
            if (cities == null)
            {
                return HttpNotFound();
            }
            var cityView = Mapper.Map<CityView>(cities);

            return View(cityView);
        }

        public ActionResult List(string sortFilter, string searchFilter, int? page)
        {
            sortFilter = sortFilter ?? "Id ascending";
            ViewBag.sortFilter = sortFilter;
            ViewBag.searchFilter = searchFilter;

            IEnumerable<City> cities = db.Cities.GetAll();

            //ViewBag.countryId = countryId;
            //if (countryId.HasValue)
            //{
            //    cities = cities.Where(c => c.CountryId == countryId);
            //}

            if (!String.IsNullOrEmpty(searchFilter))
            {
                cities = cities.Where(c => c.Name.Contains(searchFilter));
            }

            IEnumerable<CityInfo> citiesInfo = Mapper.Map<List<CityInfo>>(cities);

            citiesInfo = citiesInfo.OrderBy(sortFilter);

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(citiesInfo.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cityModel = db.Cities.GetOne(id.Value);

            if (cityModel == null)
            {
                return HttpNotFound();
            }

            var cityView = Mapper.Map<CityModify>(cityModel);

            ViewBag.Countries = db.Countries.GetDictionary();

            return View(cityView);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CityModify cityView, HttpPostedFileBase picture)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Please check all values and try again!");
                return View(cityView);
            }

            if (db.Cities.GetByName(cityView.Name, cityView.CountryId) != null)
            {
                ModelState.AddModelError(string.Empty, "This city is epsent on the site!");
                return View(cityView);
            }

            try
            {
                var cityModel = Mapper.Map<City>(cityView);
                db.Cities.Update(cityModel);

                if (picture.ContentLength > 0)
                {
                    var directoryPath = Path.Combine(Server.MapPath("~/Pictures/City"), cityModel.Id.ToString());
                    Directory.CreateDirectory(directoryPath);
                    var filePath = Path.Combine(directoryPath, "main.jpg");
                    picture.SaveAs(filePath);
                }

                db.Save();

                return View(cityView);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again.");

                return View(cityView);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Add()
        {
            PopulateCountriesDropDownList();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CityModify cityView, HttpPostedFileBase picture)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Please check all values and try again!");
                PopulateCountriesDropDownList(cityView.CountryId);
                return View(cityView);
            }

            if (db.Cities.GetByName(cityView.Name, cityView.CountryId) != null)
            {
                ModelState.AddModelError(string.Empty, "This city is already exist on our site!");
                PopulateCountriesDropDownList(cityView.CountryId);
                return View(cityView);
            }

            var cityModel = Mapper.Map<City>(cityView);
            var addedCity = db.Cities.Add(cityModel);
            db.Save();

            if (picture?.ContentLength > 0)
            {
                var directoryPath = Path.Combine(Server.MapPath("~/Images/City"), addedCity.Id.ToString());
                Directory.CreateDirectory(directoryPath);
                var filePath = Path.Combine(directoryPath, "1.jpg");
                picture.SaveAs(filePath);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            var coordinates = db.Cities.GetAll().Select(p => new CityCoord
            {
                Latitude = p.Latitude,
                Longitude = p.Longitude,
                CityId = p.Id,
                CityName = p.Name
            });

            var model = new CityIndex()
            {
                CoordinatesJson = JsonConvert.SerializeObject(coordinates, Formatting.None)
            };

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult MostReviewedCities(int count = 4)
        {
            var citiesModel = db.Cities.MostReviewedCities(count);
            var citiesView = Mapper.Map<List<CityInfo>>(citiesModel);

            return PartialView("_citiesCards", citiesView);
        }

        private void PopulateCitiesDropDownList(int? cityId = null)
        {
            var cities = db.Cities.GetAll().Select(c => new { c.Id, c.Name });
            ViewBag.Cities = new SelectList(cities, "Id", "Name", cityId);
        }

        private void PopulateCountriesDropDownList(int? cityId = null)
        {
            ViewBag.Countries = db.Countries.GetDictionary();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }


}

CityArrayWeb/Controllers/ReviewsController.cs
using AutoMapper;
using CityArrayDAL.Model;
using CityArrayDAL.UnitOfWork;
using CityArrayWeb.ModelView;
using log4net;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using Microsoft.AspNet.Identity;

namespace CityArrayWeb.Controllers
{
    public class ReviewsController : Controller
    {
        private IRepo db;
        private ILog logger;

        public ReviewsController(IRepo repo)
        {
            db = repo;
            logger = LogManager.GetLogger(this.GetType());
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string sortFilter, string searchFilter, int? page)
        {
            sortFilter = sortFilter ?? "Id ascending";
            ViewBag.sortFilter = sortFilter;
            ViewBag.searchFilter = searchFilter;

            IEnumerable<Review> reviews = db.Reviews.GetAll();

            if (!String.IsNullOrEmpty(searchFilter))
            {
                reviews = reviews.Where(r => r.City.Name.Contains(searchFilter));
            }

            IEnumerable<ReviewInfo> reviewsShort = Mapper.Map<List<ReviewInfo>>(reviews);

            reviewsShort = reviewsShort.OrderBy(sortFilter);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(reviewsShort.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ListByCity(int? cityId)
        {
            //var cityId = db.Reviews.GetOne(reviewId).City.Id;
            //var reviews = db.Reviews.GetAll().Where(c => c.City.Id == cityId && c.Id != reviewId).Take(count);
            //var reviewsShort = Mapper.Map<List<ReviewInfo>>(reviews);

            return View();
        }

        public ActionResult ListByPerson(int? personId)
        {            
            var reviews = db.Reviews.GetAll().Where(c => c.Person.Id == personId);
            var reviewsShort = Mapper.Map<List<ReviewInfo>>(reviews);

            return View(reviewsShort);
        }

        public ActionResult Info(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var review = db.Reviews.GetOne(id.GetValueOrDefault());
            if (review == null)
            {
                return HttpNotFound();
            }
            var reviewView = Mapper.Map<ReviewView>(review);

            return View(reviewView);
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult Add()
        {
            PopulateCitiesDropDownList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="User")]
        public ActionResult Add(ReviewModify review)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some problems in input data. Please repeate!");
                PopulateCitiesDropDownList(int.Parse(review.CityId));
                return View(review);
            }
            try
            {
                var reviewModel = Mapper.Map<Review>(review);
                reviewModel.CreationDate = DateTime.Today;
                reviewModel.PersonId = User.Identity.GetUserId<int>();
                db.Reviews.Add(reviewModel);
                db.Save();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Some problems on server. Please repeate!");
                PopulateCitiesDropDownList(int.Parse(review.CityId));
                return View(review);
            }
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var review = db.Reviews.GetOne(id.Value);
            if (review == null)
            {
                return HttpNotFound();
            }
            Mapper.Map<ReviewModify>(review);

            return View(review);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ReviewModify review)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some problems in input data. Please repeate!");
                PopulateCitiesDropDownList(int.Parse(review.CityId));
                return View(review);
            }
            try
            {
                var reviewModel = Mapper.Map<Review>(review);
                reviewModel.CreationDate = DateTime.Today;
                reviewModel.PersonId = 1;
                db.Reviews.Add(reviewModel);
                db.Save();
                return View();
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Some problems on server. Please repeate!");
                PopulateCitiesDropDownList(int.Parse(review.CityId));
                return View(review);
            }
        }

        [ChildActionOnly]
        public ActionResult RecentReviews(int count = 4)
        {
            var reviews = db.Reviews.GetAll().OrderByDescending(p=>p.CreationDate).Take(count);
            var reviewsView = Mapper.Map<List<ReviewInfo>>(reviews);

            return PartialView("_ReviewsCards", reviewsView);
        }

        [ChildActionOnly]
        public ActionResult RecentCityReviews(int cityId, int count = 4)
        {
            var reviews = db.Reviews.GetAll().Where(p=>p.CityId == cityId).OrderByDescending(p => p.CreationDate).Take(count);
            var reviewsView = Mapper.Map<List<ReviewInfo>>(reviews);

            return PartialView("_ReviewsCards", reviewsView);
        }

        [ChildActionOnly]
        public ActionResult RecommendedReviews(int reviewId, int count)
        {
            var cityId = db.Reviews.GetOne(reviewId).City.Id;
            var reviews = db.Reviews.GetAll().Where(c => c.City.Id == cityId && c.Id != reviewId).Take(count);
            var reviewsShort = Mapper.Map<List<ReviewInfo>>(reviews);

            return PartialView("_ReviewsCards", reviewsShort);
        }

        private void PopulateCitiesDropDownList(int? cityId = null)
        {
            ViewBag.Cities = db.Cities.GetDictionary();
        }

        private void PopulateCountriesDropDownList(int? cityId = null)
        {
            ViewBag.Countries = db.Countries.GetDictionary();
        }
    }
}

CityArrayWeb/Controllers/WishesController.cs
using AutoMapper;
using CityArrayDAL.UnitOfWork;
using CityArrayWeb.ModelView;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CityArrayWeb.Controllers
{
    public class WishesController : Controller
    {
        private IRepo db;
        private ILog logger;

        public WishesController(IRepo repo)
        {
            db = repo;
            logger = LogManager.GetLogger(this.GetType());
        }

        [ChildActionOnly]
        public ActionResult RecentWishes(int count=4)
        {
            var wishes = db.Wishes.GetAll().OrderByDescending(p=>p.Date).Take(count);
            var wishesView = Mapper.Map<List<WishedCityView>>(wishes);
            return PartialView("_WishesCards", wishesView);                
        }

        public void Add(int? id)
        {

        }

    }
}

CityArrayWeb/Views/City/Add.cshtml
@model CityArrayWeb.ModelView.CityModify
@{
                /**/

                /**/

                ViewBag.Title = "AddCity";
}

<h2>Add City</h2>
<hr />

@using (Html.BeginForm("Add", "City", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CountryId, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            <select class="selectpicker" data-live-search="true" name="CountryId">
                <option>Select Country</option>

                @foreach (var country in ViewBag.Countries)
                {
                    <option value="@country.Value">@country.Key</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IsCapital, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.CheckBoxFor(m => m.IsCapital)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Latitude, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(m => m.Latitude, new { @class = "form-control", rows = "4" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Longitude, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(m => m.Longitude, new { @class = "form-control", rows = "4" })
        </div>
    </div>



    <div class="form-group">
        <label class="col-sm-2 control-label">Picture</label>
        <div class="col-sm-10">
            <input class="btn btn-default" type="file" id="Picture" name="picture">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;
                Add
            </button>
            &nbsp;|&nbsp;
            <a href="@Url.Action("Index")"><span class="glyphicon glyphicon-list"></span>&nbsp;Back to list</a>
        </div>
    </div>


}

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityArrayWeb/Views/City/Edit.cshtml
@model CityArrayWeb.ModelView.CityView

@{
    ViewBag.Title = "EditCity";
}

<h2>EditCity</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CityViewPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CountryId, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <select class="selectpicker" data-live-search="true" name="CountryId">
                    <option @Model.CountryId>@Model.CountryName</option>

                    @foreach (var country in ViewBag.Countries)
                    {
                        <option value="@country.Value">@country.Key</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCapital, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCapital)
                    @Html.ValidationMessageFor(model => model.IsCapital, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SomeData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SomeData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SomeData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Picture</label>
            <div class="col-sm-10">
                <input class="btn btn-default" type="file" id="Picture" name="Picture">
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CityArrayWeb/Views/City/Index.cshtml
@using CityArrayWeb
@using CityArrayWeb.Controllers
@using CityArrayWeb.ModelView
@model CityIndex
@{
    ViewBag.Title = "Main";
}

<h2>Main</h2>

<div id="map" class="big-map"></div>

@if (User.IsInRole("user"))
{
    <a href="@Url.Action(nameof(CityController.Add))" class="btn btn-default">Add new City</a>
}

<a href="@Url.Action(nameof(CityController.List))" class="btn btn-default">Show all cities</a>


<h3>Most Reviewed cities :</h3>
@Html.Action(nameof(CityController.MostReviewedCities), "City")

<h3>Last reviews :</h3>
@Html.Action(nameof(ReviewsController.RecentReviews), "Reviews")

<h3>Last wishes :</h3>
@Html.Action(nameof(WishesController.RecentWishes), "Wishes")

@section scripts{
    <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHN84SGaz7Lv1B9I0GpYWwv-o2i5SZZew"></script>
    <script type="text/javascript">
        var cities = @Html.Raw(Model.CoordinatesJson);

        var map;
        var infoWindow;

        window.onload = function () {
            showMap();
        }

        function showMap() {
            var mapOptions = {
                zoom: 2,
                center: new google.maps.LatLng(20, 20)
            };
            var mapDiv = document.getElementById("map");
            map = new google.maps.Map(mapDiv, mapOptions);

            infoWindow = new google.maps.InfoWindow();

            google.maps.event.addListener(map, 'click', function () {
                infoWindow.close();
            });

            cities.map(function (item, i) {
                LatLng = new google.maps.LatLng(item.Latitude, item.Longitude);
                var marker = new google.maps.Marker({
                    map: map,
                    position: LatLng,
                    title: item.CityName
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infoWindow.close();
                    infoWindow = new google.maps.InfoWindow();
                    infoWindow.setContent(item.CityName);
                    infoWindow.open(map, marker);
                });
            });


        }
    </script>
}

CityArrayWeb/Views/City/Info.cshtml
@model CityArrayWeb.ModelView.CityView

@{
    ViewBag.Title = "Info";
}

<h2>Info</h2>

@if (User.IsInRole("Admin"))
{
    <a href="@Url.Action(nameof(CityController.Edit),new {id=Model.Id})" class="btn btn-default">Modify city</a>
}

@if (User.IsInRole("User"))
{
    <a href="@Url.Action(nameof(ReviewsController.Add),"Reviews")" class="btn btn-default">Add review</a>
    <a href="@Url.Action(nameof(WishesController.Add),"Wishes")" class="btn btn-default">Add to wishes</a>
}
@*<a href="@Url.Action(nameof(ReviewsController.CityList),"Reviews")" class="btn btn-default">Show city reviews</a>*@

<div>
    <h4>CityView</h4>
    <hr />
    <div id="map"></div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCapital)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCapital)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @MyHelpers.SetRating(Model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewsCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WishesCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WishesCount)
        </dd>


    </dl>
    <div id="Latitude" hidden>@Model.Latitude</div>
    <div id="Longitude" hidden>@Model.Longitude</div>

    <hr />

    @Html.Action(nameof(ReviewsController.RecentCityReviews),"Reviews",new {cityId=Model.Id, count = 8})

</div>


@section scripts{
    <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHN84SGaz7Lv1B9I0GpYWwv-o2i5SZZew"></script>
    @Scripts.Render("~/bundles/maps")
}

CityArrayWeb/Views/City/List.cshtml
@using CityArrayWeb.Components
@using CityArrayWeb.ModelView
@using PagedList.Mvc;
@model PagedList.IPagedList<CityInfo>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm(nameof(CityController.List), "City", FormMethod.Get))
{
    <p>
        Search by name: @Html.TextBox("searchFilter", ViewBag.searchFilter as string)
        <br />
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        @Html.TableHeadRowSortable(typeof(CityInfo),"City",  nameof(CityController.List),
                 (string)ViewBag.sortFilter, (string)ViewBag.searchFilter)
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, nameof(CityController.Info), new { id = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CountryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCapital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewsCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WishesCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action(nameof(CityController.List),
    new { page, sortFilter = ViewBag.sortFilter, searchFilter = ViewBag.searchFilter }))